<?php

use App\Models\Profile;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'api/billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth', 'can:manage-billing'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

    'brand' =>  [
        // 'logo' => realpath(__DIR__.'/../public/svg/billing-logo.svg'),
        'color' => 'bg-blue-700',
    ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::billingAddressCollection(),
        // Features::mustAcceptTerms(),
        Features::euVatCollection(['home-country' => 'GB']),
        // Features::receiptEmails(['custom-addresses' => true]),
        Features::paymentNotificationEmails(),
    ],


    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Your Product',
        'product' => 'Your Product',
        'street' => '111 Example St.',
        'location' => 'Los Angeles, CA',
        'phone' => '555-555-5555',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    // @todo: check subscription billables between App central and App tenant
    'billables' => [
        'user' => [
            'model' => Profile::class,

            'trial_days' => 0, // test new tenancy Profile before apply 

            'default_interval' => 'monthly',

            // Do not remove existing plans on LIVE website - it will cause error
            'plans' => [
                [
                    'name'              => 'Demo Package',
                    'short_description' => 'Just like Standard Package but with limited features',
                    'monthly_id'        => 'Demo', // IMPORATNT: do not change
                    'trial_days'        => 99999, // IMPORATNT: do not change
                    'features'  => [
                        '1 Contract',
                        '3 Users',
                        '2GB max storage',
                        'etc.',
                    ],
                ],
                // [
                //     'name' => 'Standard Package',
                //     'short_description' => 'Minimum of 5 users',
                //     'monthly_id' => env('SPARK_PLAN_1_MONTHLY'),
                //     'yearly_id' => env('SPARK_PLAN_1_YEARLY'),
                //     'yearly_incentive' => 'That\'s 2 months for free',
                //     'features' => [
                //         // 'Feature 1',
                //         // 'Feature 2',
                //         // 'Feature 3',
                //     ],
                // ],
            ],
        ],
    ]
];
